---
title: "Basic demo"
author: "Michael Barkasi"
date: '`r Sys.Date()`'
---

```{r setup, include = FALSE}
options(width = 10000)
knitr::opts_chunk$set(class.output = "scroll-output", cache = TRUE)
library(FISHmQC)
```

## Introduction 

Grab MERSCOPE codebook. Must have row names in the first column giving species names. 

```{r get_codebook}
file_path <- system.file(
  "extdata",
  "codebook_obs.csv",
  package = "FISHmQC"
)
codebook <- read.csv(file_path, row.names = 1)
```

Some text here. 

```{r set_max_Hamming}
max_correctable_Hamming_distance <- 3
```

Get summary stats 


```{r make_count_data, eval = FALSE}
data_path_cells <- "/Users/michaelbarkasi/projects_Oviedo_lab/_molecular_mechanisms_of_ACx_lateralization/data_ACx_cells"
count_data <- wispack::make_count_data(
  data_path = data_path_cells, 
  remove_L1 = FALSE, 
  ROI_only = FALSE,
  raw = TRUE,
  drop_blanks = FALSE,
  verbose = TRUE
)
count_data <- count_data$count_data
```

Now make summary stats, for each mouse 

```{r summary_stats, eval = FALSE}
mice <- unique(count_data$mouse)
mice_masks <- lapply(mice, function(m) count_data$mouse == m)
count_data <- count_data[,13:(ncol(count_data)-6)]
summary_stats_data <- data.frame(mouse = c(), rates = c(), variance = c(), counts = c())
for (i in seq_along(mice_masks)) {
  ss <- summary_stats_from_data(count_data[mice_masks[[i]],])
  ss <- cbind(mouse = i, ss)
  summary_stats_data <- rbind(summary_stats_data, ss)
}
write.csv(
  summary_stats_data,
  file = "/Users/michaelbarkasi/projects_Oviedo_lab/R_packages/FISHmQC/inst/extdata/summary_stats_all_mice.csv",
  row.names = TRUE
)
```

```{r align_names}
file_path <- system.file(
  "extdata",
  "summary_stats_all_mice.csv",
  package = "FISHmQC"
)
summary_stats_data <- read.csv(file_path, row.names = 1)

m1_summary_stats <- summary_stats_data[summary_stats_data$mouse == 1,]

species_names <- rownames(m1_summary_stats)
rownames(codebook) <- gsub("-", ".", rownames(codebook))
codebook <- codebook[species_names,]
blank_mask <- grepl("Blank", species_names)
gene_rate_order <- order(m1_summary_stats$rates[!blank_mask], decreasing = TRUE)
blank_rate_order <- order(m1_summary_stats$rates[blank_mask], decreasing = TRUE)
m1_summary_stats <- rbind(
  m1_summary_stats[!blank_mask,][gene_rate_order,],
  m1_summary_stats[blank_mask,][blank_rate_order,]
)
codebook <- rbind(
  codebook[!blank_mask,][gene_rate_order,],
  codebook[blank_mask,][blank_rate_order,]
)
```

Now try new function. 

```{r new_initial_estimate}
bc_counts <- as.matrix(m1_summary_stats[,c("rates", "variance", "counts")])
rownames(bc_counts) <- rownames(m1_summary_stats)
cb <- as.matrix(codebook)
t <- Sys.time()
test_results <- mQC(
  bc_counts, 
  cb, 
  max_correctable_Hamming_distance,
  0.1,   # max_fr
  1e-6,   # ctol
  100,    # max_evals
  "SBPLX", # COBYLA, CRS2, NELDERMEAD, SBPLX, PRAXIS, ESCH, ISRES, DIRECT, DIRECT_L
  4,  # Number of times to rerun a simulation when predicting counts as a way to estimate likelihood of observed counts given a set of bit-flip rates; values >1 help to smooth out stochastic noise
  10,  # Expected number of transcripts for least abundant barcode, used to set counts in simulations from rates
  100, # Number of times to simulate a given set of flip rates, to get distribution of CR and PPV values
  5    # n_forks
  )
d <- Sys.time() - t
units(d) <- "secs"
cat("\ntime:", d, "seconds\n")
```

```{r plot_results}
plot_df <- data.frame(
  observed = test_results$counts_provided[,"counts"], 
  predicted = test_results$expected_counts, 
  bc = seq_len(nrow(bc_counts))
  )
ggplot(plot_df, aes(x = bc)) + 
  geom_point(aes(y = observed), color = "blue") + 
  geom_point(aes(y = predicted), color = "red") + 
  theme_minimal() + 
  scale_y_log10() +
  labs(title = "Observed vs Predicted Counts", x = "Barcode Index", y = "Counts") + 
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
plot(test_results$rate01, col = "blue", pch = 16, xlab = "Bit Index", ylab = "Flip Rate", main = "Estimated Bit Flip Rates", ylim = c(0, max(c(test_results$rate01, test_results$rate10))+0.1))
points(test_results$rate10, col = "red", pch = 16)
plot(test_results$eval_history)
```
