// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// unique_Hamming_cb
IntegerVector unique_Hamming_cb(const IntegerMatrix& codebook);
RcppExport SEXP _flipFISH_unique_Hamming_cb(SEXP codebookSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type codebook(codebookSEXP);
    rcpp_result_gen = Rcpp::wrap(unique_Hamming_cb(codebook));
    return rcpp_result_gen;
END_RCPP
}
// mQC
List mQC(NumericMatrix bc_counts, IntegerMatrix codebook, int max_correctable_Hamming_distance, NumericVector step_size, NumericVector temp, double max_fr, double max_corr, double initial_corr, double corr_step_scale, double rate10_scale, int n_steps, int n_forks, int ran_seed);
RcppExport SEXP _flipFISH_mQC(SEXP bc_countsSEXP, SEXP codebookSEXP, SEXP max_correctable_Hamming_distanceSEXP, SEXP step_sizeSEXP, SEXP tempSEXP, SEXP max_frSEXP, SEXP max_corrSEXP, SEXP initial_corrSEXP, SEXP corr_step_scaleSEXP, SEXP rate10_scaleSEXP, SEXP n_stepsSEXP, SEXP n_forksSEXP, SEXP ran_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bc_counts(bc_countsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type codebook(codebookSEXP);
    Rcpp::traits::input_parameter< int >::type max_correctable_Hamming_distance(max_correctable_Hamming_distanceSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type step_size(step_sizeSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type temp(tempSEXP);
    Rcpp::traits::input_parameter< double >::type max_fr(max_frSEXP);
    Rcpp::traits::input_parameter< double >::type max_corr(max_corrSEXP);
    Rcpp::traits::input_parameter< double >::type initial_corr(initial_corrSEXP);
    Rcpp::traits::input_parameter< double >::type corr_step_scale(corr_step_scaleSEXP);
    Rcpp::traits::input_parameter< double >::type rate10_scale(rate10_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type n_steps(n_stepsSEXP);
    Rcpp::traits::input_parameter< int >::type n_forks(n_forksSEXP);
    Rcpp::traits::input_parameter< int >::type ran_seed(ran_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(mQC(bc_counts, codebook, max_correctable_Hamming_distance, step_size, temp, max_fr, max_corr, initial_corr, corr_step_scale, rate10_scale, n_steps, n_forks, ran_seed));
    return rcpp_result_gen;
END_RCPP
}
// mQC_init
List mQC_init(NumericMatrix bc_counts, IntegerMatrix codebook, int max_correctable_Hamming_distance, double max_fr, double initial_corr, double rate10_scale, int n_forks);
RcppExport SEXP _flipFISH_mQC_init(SEXP bc_countsSEXP, SEXP codebookSEXP, SEXP max_correctable_Hamming_distanceSEXP, SEXP max_frSEXP, SEXP initial_corrSEXP, SEXP rate10_scaleSEXP, SEXP n_forksSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bc_counts(bc_countsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type codebook(codebookSEXP);
    Rcpp::traits::input_parameter< int >::type max_correctable_Hamming_distance(max_correctable_Hamming_distanceSEXP);
    Rcpp::traits::input_parameter< double >::type max_fr(max_frSEXP);
    Rcpp::traits::input_parameter< double >::type initial_corr(initial_corrSEXP);
    Rcpp::traits::input_parameter< double >::type rate10_scale(rate10_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type n_forks(n_forksSEXP);
    rcpp_result_gen = Rcpp::wrap(mQC_init(bc_counts, codebook, max_correctable_Hamming_distance, max_fr, initial_corr, rate10_scale, n_forks));
    return rcpp_result_gen;
END_RCPP
}
// mQC_msle
double mQC_msle(NumericVector params, SEXP data_ptr_sexp);
RcppExport SEXP _flipFISH_mQC_msle(SEXP paramsSEXP, SEXP data_ptr_sexpSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< SEXP >::type data_ptr_sexp(data_ptr_sexpSEXP);
    rcpp_result_gen = Rcpp::wrap(mQC_msle(params, data_ptr_sexp));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flipFISH_unique_Hamming_cb", (DL_FUNC) &_flipFISH_unique_Hamming_cb, 1},
    {"_flipFISH_mQC", (DL_FUNC) &_flipFISH_mQC, 13},
    {"_flipFISH_mQC_init", (DL_FUNC) &_flipFISH_mQC_init, 7},
    {"_flipFISH_mQC_msle", (DL_FUNC) &_flipFISH_mQC_msle, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_flipFISH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
