// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// correlation_from_params
Eigen::MatrixXd correlation_from_params(const std::vector<double>& theta, int n);
RcppExport SEXP _flipFISH_correlation_from_params(SEXP thetaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(correlation_from_params(theta, n));
    return rcpp_result_gen;
END_RCPP
}
// unique_Hamming_cb
IntegerVector unique_Hamming_cb(const IntegerMatrix& codebook);
RcppExport SEXP _flipFISH_unique_Hamming_cb(SEXP codebookSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type codebook(codebookSEXP);
    rcpp_result_gen = Rcpp::wrap(unique_Hamming_cb(codebook));
    return rcpp_result_gen;
END_RCPP
}
// mQC
List mQC(NumericMatrix bc_counts, IntegerMatrix codebook, int maxHam, int n_forks, int max_flips, int report_freq, int maxeval, List fliprate_priors, double blank_weight, double prior_weight, double dispersion_weight, NumericVector obs_erc, double erc_weight, int n_restarts, bool use_mcmcsa, double mcmcsa_step_hi, double mcmcsa_step_lo, double mcmcsa_temp_hi, double mcmcsa_temp_lo, int mcmcsa_seed);
RcppExport SEXP _flipFISH_mQC(SEXP bc_countsSEXP, SEXP codebookSEXP, SEXP maxHamSEXP, SEXP n_forksSEXP, SEXP max_flipsSEXP, SEXP report_freqSEXP, SEXP maxevalSEXP, SEXP fliprate_priorsSEXP, SEXP blank_weightSEXP, SEXP prior_weightSEXP, SEXP dispersion_weightSEXP, SEXP obs_ercSEXP, SEXP erc_weightSEXP, SEXP n_restartsSEXP, SEXP use_mcmcsaSEXP, SEXP mcmcsa_step_hiSEXP, SEXP mcmcsa_step_loSEXP, SEXP mcmcsa_temp_hiSEXP, SEXP mcmcsa_temp_loSEXP, SEXP mcmcsa_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bc_counts(bc_countsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type codebook(codebookSEXP);
    Rcpp::traits::input_parameter< int >::type maxHam(maxHamSEXP);
    Rcpp::traits::input_parameter< int >::type n_forks(n_forksSEXP);
    Rcpp::traits::input_parameter< int >::type max_flips(max_flipsSEXP);
    Rcpp::traits::input_parameter< int >::type report_freq(report_freqSEXP);
    Rcpp::traits::input_parameter< int >::type maxeval(maxevalSEXP);
    Rcpp::traits::input_parameter< List >::type fliprate_priors(fliprate_priorsSEXP);
    Rcpp::traits::input_parameter< double >::type blank_weight(blank_weightSEXP);
    Rcpp::traits::input_parameter< double >::type prior_weight(prior_weightSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion_weight(dispersion_weightSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type obs_erc(obs_ercSEXP);
    Rcpp::traits::input_parameter< double >::type erc_weight(erc_weightSEXP);
    Rcpp::traits::input_parameter< int >::type n_restarts(n_restartsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mcmcsa(use_mcmcsaSEXP);
    Rcpp::traits::input_parameter< double >::type mcmcsa_step_hi(mcmcsa_step_hiSEXP);
    Rcpp::traits::input_parameter< double >::type mcmcsa_step_lo(mcmcsa_step_loSEXP);
    Rcpp::traits::input_parameter< double >::type mcmcsa_temp_hi(mcmcsa_temp_hiSEXP);
    Rcpp::traits::input_parameter< double >::type mcmcsa_temp_lo(mcmcsa_temp_loSEXP);
    Rcpp::traits::input_parameter< int >::type mcmcsa_seed(mcmcsa_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(mQC(bc_counts, codebook, maxHam, n_forks, max_flips, report_freq, maxeval, fliprate_priors, blank_weight, prior_weight, dispersion_weight, obs_erc, erc_weight, n_restarts, use_mcmcsa, mcmcsa_step_hi, mcmcsa_step_lo, mcmcsa_temp_hi, mcmcsa_temp_lo, mcmcsa_seed));
    return rcpp_result_gen;
END_RCPP
}
// test_fr_recovery
List test_fr_recovery(NumericMatrix bc_counts, IntegerMatrix codebook, int n_sims, int maxHam, int n_forks, int max_flips, int report_freq, int maxeval, List fliprate_priors, double blank_weight, double prior_weight, double dispersion_weight, double erc_weight, int n_restarts, bool use_mcmcsa, double mcmcsa_step_hi, double mcmcsa_step_lo, double mcmcsa_temp_hi, double mcmcsa_temp_lo, int mcmcsa_seed);
RcppExport SEXP _flipFISH_test_fr_recovery(SEXP bc_countsSEXP, SEXP codebookSEXP, SEXP n_simsSEXP, SEXP maxHamSEXP, SEXP n_forksSEXP, SEXP max_flipsSEXP, SEXP report_freqSEXP, SEXP maxevalSEXP, SEXP fliprate_priorsSEXP, SEXP blank_weightSEXP, SEXP prior_weightSEXP, SEXP dispersion_weightSEXP, SEXP erc_weightSEXP, SEXP n_restartsSEXP, SEXP use_mcmcsaSEXP, SEXP mcmcsa_step_hiSEXP, SEXP mcmcsa_step_loSEXP, SEXP mcmcsa_temp_hiSEXP, SEXP mcmcsa_temp_loSEXP, SEXP mcmcsa_seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bc_counts(bc_countsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type codebook(codebookSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< int >::type maxHam(maxHamSEXP);
    Rcpp::traits::input_parameter< int >::type n_forks(n_forksSEXP);
    Rcpp::traits::input_parameter< int >::type max_flips(max_flipsSEXP);
    Rcpp::traits::input_parameter< int >::type report_freq(report_freqSEXP);
    Rcpp::traits::input_parameter< int >::type maxeval(maxevalSEXP);
    Rcpp::traits::input_parameter< List >::type fliprate_priors(fliprate_priorsSEXP);
    Rcpp::traits::input_parameter< double >::type blank_weight(blank_weightSEXP);
    Rcpp::traits::input_parameter< double >::type prior_weight(prior_weightSEXP);
    Rcpp::traits::input_parameter< double >::type dispersion_weight(dispersion_weightSEXP);
    Rcpp::traits::input_parameter< double >::type erc_weight(erc_weightSEXP);
    Rcpp::traits::input_parameter< int >::type n_restarts(n_restartsSEXP);
    Rcpp::traits::input_parameter< bool >::type use_mcmcsa(use_mcmcsaSEXP);
    Rcpp::traits::input_parameter< double >::type mcmcsa_step_hi(mcmcsa_step_hiSEXP);
    Rcpp::traits::input_parameter< double >::type mcmcsa_step_lo(mcmcsa_step_loSEXP);
    Rcpp::traits::input_parameter< double >::type mcmcsa_temp_hi(mcmcsa_temp_hiSEXP);
    Rcpp::traits::input_parameter< double >::type mcmcsa_temp_lo(mcmcsa_temp_loSEXP);
    Rcpp::traits::input_parameter< int >::type mcmcsa_seed(mcmcsa_seedSEXP);
    rcpp_result_gen = Rcpp::wrap(test_fr_recovery(bc_counts, codebook, n_sims, maxHam, n_forks, max_flips, report_freq, maxeval, fliprate_priors, blank_weight, prior_weight, dispersion_weight, erc_weight, n_restarts, use_mcmcsa, mcmcsa_step_hi, mcmcsa_step_lo, mcmcsa_temp_hi, mcmcsa_temp_lo, mcmcsa_seed));
    return rcpp_result_gen;
END_RCPP
}
// tr_sum_check
double tr_sum_check(int bc, const std::vector<double>& rate10, const std::vector<double>& rate01, const std::vector<double>& corr1, const std::vector<double>& corr0);
RcppExport SEXP _flipFISH_tr_sum_check(SEXP bcSEXP, SEXP rate10SEXP, SEXP rate01SEXP, SEXP corr1SEXP, SEXP corr0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type bc(bcSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type rate10(rate10SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type rate01(rate01SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type corr1(corr1SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type corr0(corr0SEXP);
    rcpp_result_gen = Rcpp::wrap(tr_sum_check(bc, rate10, rate01, corr1, corr0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flipFISH_correlation_from_params", (DL_FUNC) &_flipFISH_correlation_from_params, 2},
    {"_flipFISH_unique_Hamming_cb", (DL_FUNC) &_flipFISH_unique_Hamming_cb, 1},
    {"_flipFISH_mQC", (DL_FUNC) &_flipFISH_mQC, 20},
    {"_flipFISH_test_fr_recovery", (DL_FUNC) &_flipFISH_test_fr_recovery, 20},
    {"_flipFISH_tr_sum_check", (DL_FUNC) &_flipFISH_tr_sum_check, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_flipFISH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
