// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// correlation_from_params
Eigen::MatrixXd correlation_from_params(const std::vector<double>& theta, int n);
RcppExport SEXP _flipFISH_correlation_from_params(SEXP thetaSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<double>& >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(correlation_from_params(theta, n));
    return rcpp_result_gen;
END_RCPP
}
// unique_Hamming_cb
IntegerVector unique_Hamming_cb(const IntegerMatrix& codebook);
RcppExport SEXP _flipFISH_unique_Hamming_cb(SEXP codebookSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const IntegerMatrix& >::type codebook(codebookSEXP);
    rcpp_result_gen = Rcpp::wrap(unique_Hamming_cb(codebook));
    return rcpp_result_gen;
END_RCPP
}
// mQC
List mQC(NumericMatrix bc_counts, IntegerMatrix codebook, int max_correctable_Hamming_distance, int n_forks, int max_flips, int report_freq, int maxeval, List fliprate_priors);
RcppExport SEXP _flipFISH_mQC(SEXP bc_countsSEXP, SEXP codebookSEXP, SEXP max_correctable_Hamming_distanceSEXP, SEXP n_forksSEXP, SEXP max_flipsSEXP, SEXP report_freqSEXP, SEXP maxevalSEXP, SEXP fliprate_priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bc_counts(bc_countsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type codebook(codebookSEXP);
    Rcpp::traits::input_parameter< int >::type max_correctable_Hamming_distance(max_correctable_Hamming_distanceSEXP);
    Rcpp::traits::input_parameter< int >::type n_forks(n_forksSEXP);
    Rcpp::traits::input_parameter< int >::type max_flips(max_flipsSEXP);
    Rcpp::traits::input_parameter< int >::type report_freq(report_freqSEXP);
    Rcpp::traits::input_parameter< int >::type maxeval(maxevalSEXP);
    Rcpp::traits::input_parameter< List >::type fliprate_priors(fliprate_priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(mQC(bc_counts, codebook, max_correctable_Hamming_distance, n_forks, max_flips, report_freq, maxeval, fliprate_priors));
    return rcpp_result_gen;
END_RCPP
}
// test_fr_recovery
List test_fr_recovery(NumericMatrix bc_counts, IntegerMatrix codebook, int n_sims, int max_correctable_Hamming_distance, int n_forks, int max_flips, int report_freq, int maxeval, List fliprate_priors);
RcppExport SEXP _flipFISH_test_fr_recovery(SEXP bc_countsSEXP, SEXP codebookSEXP, SEXP n_simsSEXP, SEXP max_correctable_Hamming_distanceSEXP, SEXP n_forksSEXP, SEXP max_flipsSEXP, SEXP report_freqSEXP, SEXP maxevalSEXP, SEXP fliprate_priorsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type bc_counts(bc_countsSEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type codebook(codebookSEXP);
    Rcpp::traits::input_parameter< int >::type n_sims(n_simsSEXP);
    Rcpp::traits::input_parameter< int >::type max_correctable_Hamming_distance(max_correctable_Hamming_distanceSEXP);
    Rcpp::traits::input_parameter< int >::type n_forks(n_forksSEXP);
    Rcpp::traits::input_parameter< int >::type max_flips(max_flipsSEXP);
    Rcpp::traits::input_parameter< int >::type report_freq(report_freqSEXP);
    Rcpp::traits::input_parameter< int >::type maxeval(maxevalSEXP);
    Rcpp::traits::input_parameter< List >::type fliprate_priors(fliprate_priorsSEXP);
    rcpp_result_gen = Rcpp::wrap(test_fr_recovery(bc_counts, codebook, n_sims, max_correctable_Hamming_distance, n_forks, max_flips, report_freq, maxeval, fliprate_priors));
    return rcpp_result_gen;
END_RCPP
}
// tr_sum_check
double tr_sum_check(int bc, const std::vector<double>& rate10, const std::vector<double>& rate01, const std::vector<double>& corr1, const std::vector<double>& corr0);
RcppExport SEXP _flipFISH_tr_sum_check(SEXP bcSEXP, SEXP rate10SEXP, SEXP rate01SEXP, SEXP corr1SEXP, SEXP corr0SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type bc(bcSEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type rate10(rate10SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type rate01(rate01SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type corr1(corr1SEXP);
    Rcpp::traits::input_parameter< const std::vector<double>& >::type corr0(corr0SEXP);
    rcpp_result_gen = Rcpp::wrap(tr_sum_check(bc, rate10, rate01, corr1, corr0));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_flipFISH_correlation_from_params", (DL_FUNC) &_flipFISH_correlation_from_params, 2},
    {"_flipFISH_unique_Hamming_cb", (DL_FUNC) &_flipFISH_unique_Hamming_cb, 1},
    {"_flipFISH_mQC", (DL_FUNC) &_flipFISH_mQC, 8},
    {"_flipFISH_test_fr_recovery", (DL_FUNC) &_flipFISH_test_fr_recovery, 9},
    {"_flipFISH_tr_sum_check", (DL_FUNC) &_flipFISH_tr_sum_check, 5},
    {NULL, NULL, 0}
};

RcppExport void R_init_flipFISH(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
