# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mQC <- function(bc_counts, codebook, max_correctable_Hamming_distance, max_fr = 0.25, ctol = 1e-3, max_evals = 500L, algorithm_name = "COBYLA", n_reruns = 1L, least_bc_n = 1L, n_resamples = 100L, n_forks = 4L) {
    .Call(`_FISHmQC_mQC`, bc_counts, codebook, max_correctable_Hamming_distance, max_fr, ctol, max_evals, algorithm_name, n_reruns, least_bc_n, n_resamples, n_forks)
}

